### ISSUE TITLE
SRTM1 dataset

### ISSUE THREAD

**Issue by Kiwa21** [ArduPilot/terraingen#2]
Hello @stephendade !
Is it possible to update this awesome tool to use the SRTM1 dataset (30m) rather than 90m ?
SRTM1 data are now available for the whole word here : https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/
Format is .hgt and similar to what Mavproxy srtm module use.

Thanks a lot,

**Comment by stephendade** [comment]
Nice! I'll take a look at it in the next couple of weeks.

**Comment by stephendade** [comment]
Fixed in #12
