### ISSUE TITLE
Terrain downloads may round to give neighbouring tile

### ISSUE THREAD

**Issue by shancock884** [ArduPilot/terraingen#20]
I was trying to download a single terrain tile, so I set parameters in the tool as follows:
Lat: -35.363261, Lon: 149.165230, Radius: 1km.
I was expecting tile S36E149, as the south-west corner of -35.3 is -36, but instead received tile S35E149.

From a quick look at the code, I wonder if these lines are the culprit, as does 'round' instead of 'floor' on the coordinates to get the integer values:
https://github.com/ArduPilot/terraingen/blob/master/app.py#L163-L164

Based on this, and just to check it was not only southern hemisphere related, I tried:
* 52.6, 0.6 => gives tile N53E001 instead of N52E000
* 52.4, 0.4 => correctly gives tile N52E000

**Comment by stephendade** [comment]
Thanks for reporting this - I've confirmed the issue and fixed

**Comment by shancock884** [comment]
Github didn't automatically close this (I guess because PR said "fix for" instead of "fix"!). Will close now.
